### ISSUE TITLE
ollama + streamText + tool issue

### ISSUE THREAD

**Issue by adeel-ali-atp** [vercel/ai#4700]
### Description

Hi, I've been going through seemingly a strange issue

When I try to call a tool using generateText it is working fine but same code with streamText fails to generate same response.

I tried adding onFinishStep, forced by providing system text as well. 

### Code example

import { streamText, tool } from "ai";
import { createOllama } from "ollama-ai-provider";
import { z } from "zod";
import { MODELS } from "./constant.js";

const ollama = createOllama();

const getWeatherTool = tool({
  description: "Get the current weather in the specified city",
  parameters: z.object({
    city: z.string().describe("The city to get the weather for"),
  }),
  execute: async ({ city }) => {
    return `The weather in ${city} is 25°C and sunny.`;
  },
});

const askAQuestion = async (prompt: string) => {
  const { textStream, text, steps } = await streamText({
    model: ollama(MODELS.GRANITE_3_1_DENSE),
    prompt,
    tools: {
      getWeather: getWeatherTool,
    },
    maxSteps: 2,
  });

  // for await (const text of textStream) {
  //   process.stdout.write(text);
  // }

  console.dir(await steps, { depth: null });
};

askAQuestion(`What's the weather in London?`).catch(console.error);

### AI provider

ollama-ai-provider v1.2.0

### Additional context

Package.json

 "devDependencies": {
    "tsx": "^4.19.2",
    "typescript": "^5.7.3"
  },
  "dependencies": {
    "@types/node": "^22.13.1",
    "ai": "^4.1.17",
    "dotenv": "^16.4.7",
    "ollama": "^0.5.12",
    "ollama-ai-provider": "^1.2.0",
    "zod": "^3.24.1"
  }

**Comment by lgrammel** [comment]
With ai@4.1.20 and @ai-sdk/react@1.1.10 I have reworked the resubmit mechanism. Please check if those new versions work for you (and also consider using message parts). Details can be found here: https://github.com/vercel/ai/pull/4670

**Comment by adeel-ali-atp** [comment]
sure let me try

**Comment by lgrammel** [comment]
When you use `streamText`, you need to consume the stream before the promises (like `steps`) are resolved. Your `await steps` blocks before ever consuming the stream.

**Comment by adeel-ali-atp** [comment]
Still the same @lgrammel 

I used newly added consumeStream() feature 

<img width="682" alt="Image" src="https://github.com/user-attachments/assets/2f6def3e-65ca-453b-bdf8-62343645eccb" />

**Comment by lgrammel** [comment]
Can you check for errors? https://sdk.vercel.ai/docs/ai-sdk-core/generating-text#onerror-callback

If that does not resolve it. pls file with the ollama provider https://github.com/sgomez/ollama-ai-provider

**Comment by adeel-ali-atp** [comment]
Yes, confirm is nothing in the onError event. The onFinish event yields the same response as above.

<img width="426" alt="Image" src="https://github.com/user-attachments/assets/d494f173-9de7-4dad-a52e-23f77a39f8fc" />

<img width="440" alt="Image" src="https://github.com/user-attachments/assets/60c07151-a1b2-47d6-af4c-9f027afa37fc" />

Thanks man! I'll open file it there.

**Comment by lgrammel** [comment]
Do you get anything when you log in `onChunk`?

**Comment by adeel-ali-atp** [comment]
It's a known issue and they have provided a workaround on their own repo. You can close this issue. I was able to get the tool response after following the steps. 

Thanks for guidence. 

<img width="564" alt="Image" src="https://github.com/user-attachments/assets/86baed33-f6e5-4956-90bd-4886ae0fe3ea" />

**Comment by nordwestt** [comment]
Hey @adeel-ali-atp I've fixed this in `ollama-ai-provider-v2` since it bothered me too 😄 
Should be plug and play, just update imports

@lgrammel since the `ollama-ai-provider` isn't being actively maintained for half a year (not answering issues or PR's), could you add `ollama-ai-provider-v2` to the docs for Ollama? 

I've added support for tool streaming and also ability to toggle thinking, which Ollama has gotten recently

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The failure was attributed to a third-party provider rather than the AI SDK, and the reporter resolved it with that provider's workaround. The thread is therefore primarily an external-provider support issue.

### Evidence
- `generateText` worked, while `streamText` returned empty output and no tool calls with `ollama-ai-provider`.
- The maintainer redirected the report to the third-party Ollama provider repository.
- The reporter confirmed it was a known provider issue, resolved it with `simulateStreaming: true`, and requested closure.
- A later comment requests listing a replacement Ollama provider in the docs, but this is incidental to the resolved support thread.
